---
name: GitHub CI

on:
  pull_request:
  push:
    branches:
      - main

defaults:
  run:
    shell: 'bash -Eeuo pipefail -x {0}'

jobs:

  pyvers:
    name: Enumerate supported Python versions
    runs-on: ubuntu-latest
    env:
      DEFAULT_PYTHON: '3.10'
    outputs:
      VERSIONS: ${{ steps.enumerator.outputs.VERSIONS }}
      DEFAULT: ${{ steps.enumerator.outputs.DEFAULT }}
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.DEFAULT_PYTHON }}
      - id: enumerator
        run: |
          python -m pip install tox tox-gh-actions
          VERSIONS=( $(tox -l | grep '^py' | cut -d- -f1 | sed -e 's,py\(.\)\(.*\),"\1.\2",' | sort -u -V) )
          echo "VERSIONS=[$(IFS=,; echo "${VERSIONS[*]}")]" >> $GITHUB_OUTPUT
          echo "DEFAULT=$(IFS=$'\n'; echo "${VERSIONS[*]}" | tail -1)" >> $GITHUB_OUTPUT

  build:
    name: Build python package
    runs-on: ubuntu-latest
    needs: pyvers
    strategy:
      matrix:
        python: ${{ fromJson(needs.pyvers.outputs.versions) }}
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
        with:
          # History maybe needed for documentation builds.
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install pypa/build
        run: python -m pip install build --user
      - name: Build binaries
        run: python -m build --sdist --wheel --outdir dist/
      - name: Upload source package
        if: ${{ matrix.python == needs.pyvers.outputs.default }}
        uses: actions/upload-artifact@v2
        with:
          name: sdist
          path: dist/*.tar.gz
          retention-days: 7
      - name: Upload wheel package
        if: ${{ matrix.python == needs.pyvers.outputs.default }}
        uses: actions/upload-artifact@v2
        with:
          name: wheel
          path: dist/*.whl
          retention-days: 7
